name: build

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "0 0 * * *"
  push:
    branches: main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.2
        id: docker_build
        with:
          push: true
          context: https://github.com/simulationcraft/simc.git#shadowlands
          tags: davidczech/simc:latest
          pull: true
          build-args: |
            THREADS=4
            APIKEY=${{ secrets.BATTLNET_API_TOKEN }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
